import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-change-me")
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        "DATABASE_URL", f"sqlite:///{BASE_DIR / 'workspace.db'}"
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    UPLOAD_FOLDER = os.environ.get("UPLOAD_FOLDER", str(BASE_DIR / "uploads"))
    MAX_CONTENT_LENGTH = 32 * 1024 * 1024
    SHARED_IMAGE_MAX_SOURCE_BYTES = 10 * 1024 * 1024
    SHARED_IMAGE_MAX_FILE_BYTES = 500 * 1024
    SHARED_IMAGE_PROJECT_QUOTA_BYTES = 30 * 1024 * 1024
    SHARED_IMAGE_MAX_PER_TODO = 3
    NOTE_IMAGE_MAX_SOURCE_BYTES = 10 * 1024 * 1024
    NOTE_IMAGE_MAX_FILE_BYTES = 500 * 1024
    NOTE_IMAGE_USER_QUOTA_BYTES = 50 * 1024 * 1024
    NOTE_IMAGE_MAX_PER_NOTE = 5
    QUESTION_IMAGE_MAX_SOURCE_BYTES = 10 * 1024 * 1024
    QUESTION_IMAGE_MAX_FILE_BYTES = 500 * 1024
    QUESTION_IMAGE_USER_QUOTA_BYTES = 50 * 1024 * 1024
    QUESTION_IMAGE_MAX_PER_QUESTION = 5
